aws-crt-cpp: fix build error when DEBUG_BUILD is enabled
xxhash marks its SSE2 hash functions with __attribute__((always_inline)).
It has auto-detection logic to disable this when __NO_INLINE__ is defined
(i.e. at -O0 or -fno-inline). However, when DEBUG_BUILD is enabled (i.e. -Og),
which does not define __NO_INLINE__ — so xxhash keeps always_inline.
But -Og doesn't inline aggressively enough to satisfy always_inline,
causing the following build error.

  error: inlining failed in call to 'always_inline' 'XXH3_accumulate_sse2'

Fix this issue by adding -DXXH_NO_INLINE_HINTS=1 to CFLAGS to disable
always_inline when DEBUG_BUILD is enabled.

Tested "bitbake aws-crt-cpp" build pass when DEBUG_BUILD is enabled.

Signed-off-by: Bin Cao <bin.cao.cn@windriver.com>